services:
  db:
    image: mariadb:10.5
    container_name: omeka-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omekapass
    volumes:
      - db_data:/var/lib/mysql

  omeka:
    build:
      context: .
      args:
        OMEKA_VERSION: 4.1.1  # Change to the desired Omeka S version
    container_name: omeka-app
    restart: always
    user: "www-data"
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./config/database.ini:/var/www/html/config/database.ini
      - ./files:/var/www/html/files

volumes:
  db_data:
